### ISSUE TITLE
Consider giving package name up

### ISSUE THREAD

**Issue by ALMaclaine** [lamarrr/Spell#1]
Hey,

I'm one of the maintainers of:

http://github.com/ahmetaa/dart-spell/

Would you consider transferring the spell package over to us so we can use it for an actual spell checker?

There are now several libraries involving number spelling:

https://pub.dev/packages?q=number+spell

I think it would be beneficial to the ecosystem to have 'spell' be an actual spell checker.

Thank you for your consideration

**Comment by lamarrr** [comment]
Thanks for your PR.

I also feel it will be more beneficial to the ecosystem if 'spell' was a number spelling utility which is why I chose it in the first place.

You can consider other unused names: spell-check, spell-checker, spell-checkr, etc.
I'm sure you can always find a better name.

Thanks for your time 😊
